- name: MyPlaybook_terr2
  hosts: netology2
  tasks:
    - name: Install MySQL 5.7 repo
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present

    - name: Install MySQL 5.7
      yum: 
        name:
          - mysql-community-common
#       - mysql-community-client
#       - mysql-community-server
#       - MySQL-python
        state: present

    - name: Start the MySQL service
      service: name=mysqld state=started enabled=true