- name: MyPlaybook_terr_mysql
  hosts: netology2
  tasks:
   - name: install rpm
     yum:
      name:  http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
      state: present
   - name: Update OS
     yum:
      name="*" state=latest
   - name: install mysql
     yum:
      name:  mysql-server
      state: latest
   - name: start mysql
     systemd: 
      name: mysqld 
      state: started 
      enabled: yes
   - name: check status mysql
     command: "systemctl status mysqld"
     register: result
     ignore_errors: yes
   - name: showing report
     debug:
      var: result