---
- name: MyPlaybook 2
  hosts: netology
  tasks:
   - name: install tuned
     yum:
      name: tuned
      state: latest
   - name: enable tuned
     systemd:
       name: tuned
       state: started
       enabled: yes
